name: hello-world2jerryattheedge

base: core
confinement: strict
grade: stable

version: 0.3
summary: Hello World
description: |
  This demo is intended to show how to build your first snap
  This code is part of the Snapcraft example tour at
  https://developer.ubuntu.com/snapcraft-getting-started
architectures:
  - build-on: amd64 
    run-on: amd64 
parts:
  hello:
    plugin: cmake
    source: snap/src

build-packages:
- g++
- make
- git
- sed


apps:
  hello-world:
    command: hello
    adapter: full
